
[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Dzmitry Izaitka", email = "dem214overlord@gmail.com"},
]
dependencies = []
requires-python = ">=3.11"
license = {text = "MIT"}
